Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -24,6 +24,39 @@ steps:
     replaceExistingArchive: true
   displayName: 'Criando pacote para analise'
 
+- task: CmdLine@2
+  inputs:
+    script: |
+      echo '[INFO] --- Veracode SAST - Pipeline Scan'
+      echo '[INFO] --- Downloading Pipeline Scan (Latest Version)...'
+      curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
+      unzip pipeline-scan-LATEST.zip
+      
+      echo '[INFO] --- Starting Pipeline Scan execution...'
+      java -Dpipeline.debug=true -jar pipeline-scan.jar -vid $(APIID) -vkey $(APIKEY) --file '$(caminhoPacote)' -so true --issue_details true
+      
+      STATUS=${?}           
+      if [ $STATUS -gt 0 ];
+          then
+              echo '[INFO] --- Pipeline Scan has finished.'
+              echo '[INFO] --- ' $STATUS ' flaws were found.'
+              #exit 1 #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
+      elif [ $STATUS -lt 0 ];
+          then
+              echo '[INFO] --- Pipeline Scan could not be executed...There are some errors...'
+              echo '[INFO] --- ' $STATUS
+              #exit 1 #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
+      fi
+  displayName: 'Pipeline Scan'
+
+- task: CmdLine@2
+  inputs:
+    script: |
+      export EXTRA_ARGS='--update-advisor --pull-request'
+      curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan $EXTRA_ARGS --allow-dirty
+    workingDirectory: '$(Agent.BuildDirectory)'
+  displayName: 'SCA'
+  
 - task: Veracode@3
   inputs:
     ConnectionDetailsSelection: 'Credentials'
